# Sample configuration file
mongodb:
  uri: "${MONGODB_URI}"
  name: "super_glitch_bot"
telegram:
  token: "${TELEGRAM_BOT_TOKEN}"
  api_id: "${TELEGRAM_API_ID}"
  api_hash: "${TELEGRAM_API_HASH}"
  admins:
    - 123456789
helius:
  api_key: "${HELIUS_API_KEY}"
  rpc_url: "https://mainnet.helius-rpc.com"
  ws_url: "wss://mainnet.helius-rpc.com"
assessment_interval: 120
performance_interval: 120
moralis_api_key: "${MORALIS_API_KEY}"
